/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_Args */

#ifndef _Included_com_rai_raiapi2_Args
#define _Included_com_rai_raiapi2_Args
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_Args_IGNORE_ARG
#define com_rai_raiapi2_Args_IGNORE_ARG 0L
#undef com_rai_raiapi2_Args_RESOURCE_ARG
#define com_rai_raiapi2_Args_RESOURCE_ARG 1L
#undef com_rai_raiapi2_Args_COMMAND_ARG
#define com_rai_raiapi2_Args_COMMAND_ARG 2L
#undef com_rai_raiapi2_Args_TIME_SEC_ARG
#define com_rai_raiapi2_Args_TIME_SEC_ARG 4L
#undef com_rai_raiapi2_Args_TIME_MS_ARG
#define com_rai_raiapi2_Args_TIME_MS_ARG 8L
#undef com_rai_raiapi2_Args_MEM_ARG
#define com_rai_raiapi2_Args_MEM_ARG 16L
#undef com_rai_raiapi2_Args_HELP_ARG
#define com_rai_raiapi2_Args_HELP_ARG 32L
#undef com_rai_raiapi2_Args_VERSION_ARG
#define com_rai_raiapi2_Args_VERSION_ARG 64L
#undef com_rai_raiapi2_Args_PRINTRC_ARG
#define com_rai_raiapi2_Args_PRINTRC_ARG 128L
#undef com_rai_raiapi2_Args_RCFILE_ARG
#define com_rai_raiapi2_Args_RCFILE_ARG 256L
#undef com_rai_raiapi2_Args_LIST_ARG
#define com_rai_raiapi2_Args_LIST_ARG 512L
#undef com_rai_raiapi2_Args_NO_DEFAULT_VAL
#define com_rai_raiapi2_Args_NO_DEFAULT_VAL 1024L
#undef com_rai_raiapi2_Args_BITS_ARG
#define com_rai_raiapi2_Args_BITS_ARG 2048L
/*
 * Class:     com_rai_raiapi2_Args
 * Method:    Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_Args_Create
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    add
 * Signature: (Lcom/rai/raiapi2/StringArg;I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_add__Lcom_rai_raiapi2_StringArg_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    add
 * Signature: (Lcom/rai/raiapi2/BoolArg;I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_add__Lcom_rai_raiapi2_BoolArg_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    add
 * Signature: (Lcom/rai/raiapi2/IntArg;I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_add__Lcom_rai_raiapi2_IntArg_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    add
 * Signature: (Lcom/rai/raiapi2/DoubleArg;I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_add__Lcom_rai_raiapi2_DoubleArg_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    addDefaults
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/io/OutputStream;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_addDefaults
  (JNIEnv *, jobject, jstring, jstring, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    processArgs
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_Args_processArgs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    getNumValues
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raiapi2_Args_getNumValues
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    getString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_Args_getString
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_Args_getBoolean
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    getInt
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raiapi2_Args_getInt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    getDouble
 * Signature: (Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rai_raiapi2_Args_getDouble
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    setInt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_setInt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    setBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_setBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_setDouble
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_Args_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    printRC
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_printRC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_Args
 * Method:    printHelp
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_Args_printHelp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
