/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiTimer */

#ifndef _Included_com_rai_raiapi2_RaiTimer
#define _Included_com_rai_raiapi2_RaiTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    DeleteCB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiTimer_DeleteCB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiTimer_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiTimer_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiTimer_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    GetInterval
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_RaiTimer_GetInterval
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiTimer
 * Method:    SetInterval
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiTimer_SetInterval
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
