/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiApiException */

#ifndef _Included_com_rai_raiapi2_RaiApiException
#define _Included_com_rai_raiapi2_RaiApiException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_RaiApiException_serialVersionUID
#define com_rai_raiapi2_RaiApiException_serialVersionUID -3042686055658047285LL
#undef com_rai_raiapi2_RaiApiException_BAD_SESSION
#define com_rai_raiapi2_RaiApiException_BAD_SESSION 0L
#undef com_rai_raiapi2_RaiApiException_BAD_SUBJECT
#define com_rai_raiapi2_RaiApiException_BAD_SUBJECT 1L
#undef com_rai_raiapi2_RaiApiException_BAD_RAIMSG
#define com_rai_raiapi2_RaiApiException_BAD_RAIMSG 2L
#undef com_rai_raiapi2_RaiApiException_BAD_BUFFER
#define com_rai_raiapi2_RaiApiException_BAD_BUFFER 3L
#undef com_rai_raiapi2_RaiApiException_BAD_IOCTL_PARM
#define com_rai_raiapi2_RaiApiException_BAD_IOCTL_PARM 4L
#undef com_rai_raiapi2_RaiApiException_BAD_DICT
#define com_rai_raiapi2_RaiApiException_BAD_DICT 5L
#undef com_rai_raiapi2_RaiApiException_BAD_SASS_INIT
#define com_rai_raiapi2_RaiApiException_BAD_SASS_INIT 6L
#undef com_rai_raiapi2_RaiApiException_DICT_LOAD_PENDING
#define com_rai_raiapi2_RaiApiException_DICT_LOAD_PENDING 7L
#undef com_rai_raiapi2_RaiApiException_BAD_RV
#define com_rai_raiapi2_RaiApiException_BAD_RV 8L
#undef com_rai_raiapi2_RaiApiException_UNKNOWN
#define com_rai_raiapi2_RaiApiException_UNKNOWN 9L
/* Inaccessible static: errString */
/*
 * Class:     com_rai_raiapi2_RaiApiException
 * Method:    getModule
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiApiException_getModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiApiException
 * Method:    getErrno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raiapi2_RaiApiException_getErrno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiApiException
 * Method:    getReason
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiApiException_getReason
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
