/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiSubscribe */

#ifndef _Included_com_rai_raiapi2_RaiSubscribe
#define _Included_com_rai_raiapi2_RaiSubscribe
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_RaiSubscribe_UPDATE
#define com_rai_raiapi2_RaiSubscribe_UPDATE 1L
#undef com_rai_raiapi2_RaiSubscribe_SNAP
#define com_rai_raiapi2_RaiSubscribe_SNAP 2L
#undef com_rai_raiapi2_RaiSubscribe_BOTH
#define com_rai_raiapi2_RaiSubscribe_BOTH 3L
#undef com_rai_raiapi2_RaiSubscribe_NO_PREFIX
#define com_rai_raiapi2_RaiSubscribe_NO_PREFIX 4L
#undef com_rai_raiapi2_RaiSubscribe_NO_COPY
#define com_rai_raiapi2_RaiSubscribe_NO_COPY 8L
#undef com_rai_raiapi2_RaiSubscribe_STATE_NO_MSG
#define com_rai_raiapi2_RaiSubscribe_STATE_NO_MSG 0L
#undef com_rai_raiapi2_RaiSubscribe_STATE_WILDCARD
#define com_rai_raiapi2_RaiSubscribe_STATE_WILDCARD 1L
#undef com_rai_raiapi2_RaiSubscribe_STATE_NO_HDR
#define com_rai_raiapi2_RaiSubscribe_STATE_NO_HDR 2L
#undef com_rai_raiapi2_RaiSubscribe_STATE_INITIAL
#define com_rai_raiapi2_RaiSubscribe_STATE_INITIAL 3L
#undef com_rai_raiapi2_RaiSubscribe_STATE_UPDATE
#define com_rai_raiapi2_RaiSubscribe_STATE_UPDATE 4L
#undef com_rai_raiapi2_RaiSubscribe_STATE_NOTFOUND
#define com_rai_raiapi2_RaiSubscribe_STATE_NOTFOUND 5L
#undef com_rai_raiapi2_RaiSubscribe_STATE_STALE
#define com_rai_raiapi2_RaiSubscribe_STATE_STALE 6L
#undef com_rai_raiapi2_RaiSubscribe_STATE_DROPPED
#define com_rai_raiapi2_RaiSubscribe_STATE_DROPPED 7L
/* Inaccessible static: state_str */
/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    DeleteCB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSubscribe_DeleteCB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSubscribe_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    Start
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSubscribe_Start
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    Cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSubscribe_Cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    Refresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSubscribe_Refresh
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    Subject
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiSubscribe_Subject
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSubscribe
 * Method:    InProgress
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiSubscribe_InProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
