/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiInteractivePublish */

#ifndef _Included_com_rai_raiapi2_RaiInteractivePublish
#define _Included_com_rai_raiapi2_RaiInteractivePublish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiInteractivePublish
 * Method:    DeleteCB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiInteractivePublish_DeleteCB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiInteractivePublish
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiInteractivePublish_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiInteractivePublish
 * Method:    InteractiveStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiInteractivePublish_InteractiveStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_RaiInteractivePublish
 * Method:    InteractiveCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiInteractivePublish_InteractiveCancel
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiInteractivePublish
 * Method:    InProgress
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiInteractivePublish_InProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
