/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiDict */

#ifndef _Included_com_rai_raiapi2_RaiDict
#define _Included_com_rai_raiapi2_RaiDict
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiDict
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiDict_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiDict
 * Method:    Load
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiDict_Load
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     com_rai_raiapi2_RaiDict
 * Method:    HaveDict
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiDict_HaveDict
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiDict
 * Method:    InProgress
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiDict_InProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
