/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiApi */

#ifndef _Included_com_rai_raiapi2_RaiApi
#define _Included_com_rai_raiapi2_RaiApi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_RaiApi_LVL_DEVEL
#define com_rai_raiapi2_RaiApi_LVL_DEVEL 0L
#undef com_rai_raiapi2_RaiApi_LVL_FTRACE
#define com_rai_raiapi2_RaiApi_LVL_FTRACE 1L
#undef com_rai_raiapi2_RaiApi_LVL_TRACE
#define com_rai_raiapi2_RaiApi_LVL_TRACE 2L
#undef com_rai_raiapi2_RaiApi_LVL_DEBUG
#define com_rai_raiapi2_RaiApi_LVL_DEBUG 3L
#undef com_rai_raiapi2_RaiApi_LVL_MINOR
#define com_rai_raiapi2_RaiApi_LVL_MINOR 4L
#undef com_rai_raiapi2_RaiApi_LVL_NORMAL
#define com_rai_raiapi2_RaiApi_LVL_NORMAL 5L
#undef com_rai_raiapi2_RaiApi_LVL_ERROR
#define com_rai_raiapi2_RaiApi_LVL_ERROR 6L
#undef com_rai_raiapi2_RaiApi_SIGHUP
#define com_rai_raiapi2_RaiApi_SIGHUP 1L
#undef com_rai_raiapi2_RaiApi_SIGINT
#define com_rai_raiapi2_RaiApi_SIGINT 2L
#undef com_rai_raiapi2_RaiApi_SIGTERM
#define com_rai_raiapi2_RaiApi_SIGTERM 15L
/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    RaiOpen
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Lcom/rai/raiapi2/RaiApi;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiApi_RaiOpen
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    GetApiName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiApi_GetApiName
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    RaiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiApi_RaiVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    GetArgs
 * Signature: (Lcom/rai/raiapi2/Args;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_GetArgs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    GetDictArgs
 * Signature: (Lcom/rai/raiapi2/Args;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_GetDictArgs
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    ParseArgs
 * Signature: (Lcom/rai/raiapi2/Args;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_ParseArgs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    OpenLog
 * Signature: (Lcom/rai/raiapi2/Args;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiApi_OpenLog__Lcom_rai_raiapi2_Args_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    OpenLog
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_OpenLog__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    PrintLog
 * Signature: (ILjava/lang/Exception;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_PrintLog
  (JNIEnv *, jobject, jint, jthrowable, jstring);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    Log
 * Signature: (ILjava/lang/Exception;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_Log
  (JNIEnv *, jclass, jint, jthrowable, jstring);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    OpenDict
 * Signature: (Lcom/rai/raiapi2/Args;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiApi_OpenDict
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    CreateSession
 * Signature: ()Lcom/rai/raiapi2/RaiSession;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiApi_CreateSession
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    NewRaiMsg
 * Signature: (ISSSS)Lcom/rai/raimsg/RaiMsg;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiApi_NewRaiMsg__ISSSS
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    NewRaiMsg
 * Signature: (ISLjava/lang/String;SS)Lcom/rai/raimsg/RaiMsg;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiApi_NewRaiMsg__ISLjava_lang_String_2SS
  (JNIEnv *, jclass, jint, jshort, jstring, jshort, jshort);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    RegisterSigHandler
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_RegisterSigHandler
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    SetIoctl
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_RaiApi_SetIoctl
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_rai_raiapi2_RaiApi
 * Method:    initClasses
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiApi_initClasses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
