/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiPublish */

#ifndef _Included_com_rai_raiapi2_RaiPublish
#define _Included_com_rai_raiapi2_RaiPublish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    Publish
 * Signature: (Ljava/lang/String;Lcom/rai/raimsg/RaiMsg;J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_Publish__Ljava_lang_String_2Lcom_rai_raimsg_RaiMsg_2J
  (JNIEnv *, jobject, jstring, jobject, jlong);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    Publish
 * Signature: (Ljava/lang/String;[BIIJ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_Publish__Ljava_lang_String_2_3BIIJ
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    SetPrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_SetPrefix
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    GetPrefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiPublish_GetPrefix
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    GetSeqno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_RaiPublish_GetSeqno
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    SetSeqno
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_SetSeqno
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rai_raiapi2_RaiPublish
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiPublish_Destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
