/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiQueue */

#ifndef _Included_com_rai_raiapi2_RaiQueue
#define _Included_com_rai_raiapi2_RaiQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    CreateSubscribe
 * Signature: (Lcom/rai/raiapi2/RaiMsgCallback;Ljava/lang/Object;)Lcom/rai/raiapi2/RaiSubscribe;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiQueue_CreateSubscribe
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    CreateTimer
 * Signature: (Lcom/rai/raiapi2/RaiTimerCallback;Ljava/lang/Object;)Lcom/rai/raiapi2/RaiTimer;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiQueue_CreateTimer
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    CreateInteractivePublish
 * Signature: (Lcom/rai/raiapi2/RaiSubscribeCallback;Ljava/lang/Object;)Lcom/rai/raiapi2/RaiInteractivePublish;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiQueue_CreateInteractivePublish
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    NotifyStatus
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_NotifyStatus
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    Mainloop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_Mainloop
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    TimedDispatch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_TimedDispatch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    Dispatch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_Dispatch
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    GetDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rai_raiapi2_RaiQueue_GetDepth
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiQueue
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiQueue_Destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
