/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_RaiSession */

#ifndef _Included_com_rai_raiapi2_RaiSession
#define _Included_com_rai_raiapi2_RaiSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    DeleteCB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_DeleteCB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    CreateQueue
 * Signature: (Z)Lcom/rai/raiapi2/RaiQueue;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiSession_CreateQueue
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    CreatePublish
 * Signature: ()Lcom/rai/raiapi2/RaiPublish;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiSession_CreatePublish
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    CreateDict
 * Signature: ()Lcom/rai/raiapi2/RaiDict;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiSession_CreateDict
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    Login
 * Signature: (Ljava/lang/String;)Lcom/rai/raiapi2/RaiEntitlement;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raiapi2_RaiSession_Login
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    SetDataLossCB
 * Signature: (Lcom/rai/raiapi2/RaiDataLossCallback;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_SetDataLossCB
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    NotifyStatus
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_NotifyStatus
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    SetSessionName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raiapi2_RaiSession_SetSessionName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rai_raiapi2_RaiSession
 * Method:    GetSessionName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_RaiSession_GetSessionName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
