/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_TimeRotate */

#ifndef _Included_com_rai_raiapi2_TimeRotate
#define _Included_com_rai_raiapi2_TimeRotate
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_TimeRotate_ROTATE_UNSPECIFIED
#define com_rai_raiapi2_TimeRotate_ROTATE_UNSPECIFIED 0L
#undef com_rai_raiapi2_TimeRotate_ROTATE_DAILY
#define com_rai_raiapi2_TimeRotate_ROTATE_DAILY 1L
#undef com_rai_raiapi2_TimeRotate_ROTATE_WEEKLY
#define com_rai_raiapi2_TimeRotate_ROTATE_WEEKLY 2L
#undef com_rai_raiapi2_TimeRotate_MSECS_IN_SEC
#define com_rai_raiapi2_TimeRotate_MSECS_IN_SEC 1000LL
#undef com_rai_raiapi2_TimeRotate_MSECS_IN_DAY
#define com_rai_raiapi2_TimeRotate_MSECS_IN_DAY 1440000LL
#undef com_rai_raiapi2_TimeRotate_MSECS_IN_WEEK
#define com_rai_raiapi2_TimeRotate_MSECS_IN_WEEK 10080000LL
/*
 * Class:     com_rai_raiapi2_TimeRotate
 * Method:    setRotateTime
 * Signature: (Ljava/lang/String;IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_TimeRotate_setRotateTime
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     com_rai_raiapi2_TimeRotate
 * Method:    setRotatePeriod
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raiapi2_TimeRotate_setRotatePeriod
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
