/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raiapi2_Time */

#ifndef _Included_com_rai_raiapi2_Time
#define _Included_com_rai_raiapi2_Time
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raiapi2_Time_TZ_LOCAL_TIME
#define com_rai_raiapi2_Time_TZ_LOCAL_TIME 0L
#undef com_rai_raiapi2_Time_TZ_GM_TIME
#define com_rai_raiapi2_Time_TZ_GM_TIME 1L
/*
 * Class:     com_rai_raiapi2_Time
 * Method:    currentTimeNanosecs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_Time_currentTimeNanosecs
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raiapi2_Time
 * Method:    nsTimestamp
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_Time_nsTimestamp
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_rai_raiapi2_Time
 * Method:    nsIntervalTime
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_Time_nsIntervalTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_Time
 * Method:    hiresTimeNanosecs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_Time_hiresTimeNanosecs
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raiapi2_Time
 * Method:    hiresTimeToNsTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raiapi2_Time_hiresTimeToNsTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raiapi2_Time
 * Method:    strftime
 * Signature: (IJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raiapi2_Time_strftime
  (JNIEnv *, jclass, jint, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
