/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raimsg_RaiField */

#ifndef _Included_com_rai_raimsg_RaiField
#define _Included_com_rai_raimsg_RaiField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raimsg_RaiField_Create
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiField_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiField_Name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_Type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_Size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    HintType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_HintType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    HintSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_HintSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    EntryType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_EntryType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    EntrySize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_EntrySize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    NumEntries
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_NumEntries
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Get
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiField_Get
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiField_GetBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_rai_raimsg_RaiField_GetByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_rai_raimsg_RaiField_GetShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiField_GetInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raimsg_RaiField_GetLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_rai_raimsg_RaiField_GetFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_rai_raimsg_RaiField_GetDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiField_GetString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetOpaque
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rai_raimsg_RaiField_GetOpaque
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetPartial
 * Signature: (J)Lcom/rai/raimsg/Partial;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiField_GetPartial
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetBooleanArray
 * Signature: (J)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_rai_raimsg_RaiField_GetBooleanArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rai_raimsg_RaiField_GetByteArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetShortArray
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_rai_raimsg_RaiField_GetShortArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetIntArray
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rai_raimsg_RaiField_GetIntArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetLongArray
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_rai_raimsg_RaiField_GetLongArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetFloatArray
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_rai_raimsg_RaiField_GetFloatArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetDoubleArray
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_rai_raimsg_RaiField_GetDoubleArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetStringArray
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rai_raimsg_RaiField_GetStringArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    GetHint
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiField_GetHint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Find
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiField_Find
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    First
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiField_First
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_rai_raimsg_RaiField
 * Method:    Next
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiField_Next
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
