/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raimsg_RaiMsgException */

#ifndef _Included_com_rai_raimsg_RaiMsgException
#define _Included_com_rai_raimsg_RaiMsgException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raimsg_RaiMsgException_serialVersionUID
#define com_rai_raimsg_RaiMsgException_serialVersionUID -3042686055658047285LL
/*
 * Class:     com_rai_raimsg_RaiMsgException
 * Method:    getModule
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsgException_getModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsgException
 * Method:    getErrno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsgException_getErrno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsgException
 * Method:    getReason
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsgException_getReason
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
