/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rai_raimsg_RaiMsg */

#ifndef _Included_com_rai_raimsg_RaiMsg
#define _Included_com_rai_raimsg_RaiMsg
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rai_raimsg_RaiMsg_RAIMSG_NODATA
#define com_rai_raimsg_RaiMsg_RAIMSG_NODATA 0L
#undef com_rai_raimsg_RaiMsg_RAIMSG_MESSAGE
#define com_rai_raimsg_RaiMsg_RAIMSG_MESSAGE 1L
#undef com_rai_raimsg_RaiMsg_RAIMSG_STRING
#define com_rai_raimsg_RaiMsg_RAIMSG_STRING 2L
#undef com_rai_raimsg_RaiMsg_RAIMSG_OPAQUE
#define com_rai_raimsg_RaiMsg_RAIMSG_OPAQUE 3L
#undef com_rai_raimsg_RaiMsg_RAIMSG_BOOLEAN
#define com_rai_raimsg_RaiMsg_RAIMSG_BOOLEAN 4L
#undef com_rai_raimsg_RaiMsg_RAIMSG_INT
#define com_rai_raimsg_RaiMsg_RAIMSG_INT 5L
#undef com_rai_raimsg_RaiMsg_RAIMSG_UINT
#define com_rai_raimsg_RaiMsg_RAIMSG_UINT 6L
#undef com_rai_raimsg_RaiMsg_RAIMSG_REAL
#define com_rai_raimsg_RaiMsg_RAIMSG_REAL 7L
#undef com_rai_raimsg_RaiMsg_RAIMSG_ARRAY
#define com_rai_raimsg_RaiMsg_RAIMSG_ARRAY 8L
#undef com_rai_raimsg_RaiMsg_RAIMSG_PARTIAL
#define com_rai_raimsg_RaiMsg_RAIMSG_PARTIAL 9L
#undef com_rai_raimsg_RaiMsg_RAIMSG_IPDATA
#define com_rai_raimsg_RaiMsg_RAIMSG_IPDATA 10L
#undef com_rai_raimsg_RaiMsg_RAIMSG_MAXVALID
#define com_rai_raimsg_RaiMsg_RAIMSG_MAXVALID 11L
#undef com_rai_raimsg_RaiMsg_RAIMSG_PROTO
#define com_rai_raimsg_RaiMsg_RAIMSG_PROTO 0L
#undef com_rai_raimsg_RaiMsg_RV_SASS_PROTO
#define com_rai_raimsg_RaiMsg_RV_SASS_PROTO 1L
#undef com_rai_raimsg_RaiMsg_TIB_SASS_PROTO
#define com_rai_raimsg_RaiMsg_TIB_SASS_PROTO 2L
#undef com_rai_raimsg_RaiMsg_TIB_SASS_FORM_PROTO
#define com_rai_raimsg_RaiMsg_TIB_SASS_FORM_PROTO 3L
#undef com_rai_raimsg_RaiMsg_RV_RAIMSG_PROTO
#define com_rai_raimsg_RaiMsg_RV_RAIMSG_PROTO 4L
#undef com_rai_raimsg_RaiMsg_XREP_PROTO
#define com_rai_raimsg_RaiMsg_XREP_PROTO 5L
#undef com_rai_raimsg_RaiMsg_RV_PROTO
#define com_rai_raimsg_RaiMsg_RV_PROTO 6L
#undef com_rai_raimsg_RaiMsg_CISERVER_SASS_PROTO
#define com_rai_raimsg_RaiMsg_CISERVER_SASS_PROTO 7L
#undef com_rai_raimsg_RaiMsg_CISERVER_SASS_FORM_PROTO
#define com_rai_raimsg_RaiMsg_CISERVER_SASS_FORM_PROTO 8L
#undef com_rai_raimsg_RaiMsg_BAD_ARG
#define com_rai_raimsg_RaiMsg_BAD_ARG 1L
#undef com_rai_raimsg_RaiMsg_BAD_MAGIC_NUMBER
#define com_rai_raimsg_RaiMsg_BAD_MAGIC_NUMBER 2L
#undef com_rai_raimsg_RaiMsg_NOT_FOUND
#define com_rai_raimsg_RaiMsg_NOT_FOUND 9L
#undef com_rai_raimsg_RaiMsg_NO_FIELD
#define com_rai_raimsg_RaiMsg_NO_FIELD 11L
#undef com_rai_raimsg_RaiMsg_BAD_CVT_STRING
#define com_rai_raimsg_RaiMsg_BAD_CVT_STRING 43L
#undef com_rai_raimsg_RaiMsg_BAD_CVT_BOOL
#define com_rai_raimsg_RaiMsg_BAD_CVT_BOOL 44L
#undef com_rai_raimsg_RaiMsg_BAD_CVT_INT
#define com_rai_raimsg_RaiMsg_BAD_CVT_INT 45L
#undef com_rai_raimsg_RaiMsg_BAD_CVT_REAL
#define com_rai_raimsg_RaiMsg_BAD_CVT_REAL 46L
#undef com_rai_raimsg_RaiMsg_ADD_TYPE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_TYPE_ATTR 1L
#undef com_rai_raimsg_RaiMsg_ADD_SIZE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_SIZE_ATTR 2L
#undef com_rai_raimsg_RaiMsg_ADD_FID_ATTR
#define com_rai_raimsg_RaiMsg_ADD_FID_ATTR 4L
#undef com_rai_raimsg_RaiMsg_ADD_PARTIAL_OFF_ATTR
#define com_rai_raimsg_RaiMsg_ADD_PARTIAL_OFF_ATTR 8L
#undef com_rai_raimsg_RaiMsg_ADD_ARRAY_COUNT_ATTR
#define com_rai_raimsg_RaiMsg_ADD_ARRAY_COUNT_ATTR 16L
#undef com_rai_raimsg_RaiMsg_ADD_ARRAY_TYPE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_ARRAY_TYPE_ATTR 32L
#undef com_rai_raimsg_RaiMsg_ADD_ARRAY_ELSIZE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_ARRAY_ELSIZE_ATTR 64L
#undef com_rai_raimsg_RaiMsg_ADD_HINT_ATTR
#define com_rai_raimsg_RaiMsg_ADD_HINT_ATTR 128L
#undef com_rai_raimsg_RaiMsg_ADD_HINT_TYPE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_HINT_TYPE_ATTR 256L
#undef com_rai_raimsg_RaiMsg_ADD_HINT_SIZE_ATTR
#define com_rai_raimsg_RaiMsg_ADD_HINT_SIZE_ATTR 512L
#undef com_rai_raimsg_RaiMsg_ADD_ALL_ATTRS
#define com_rai_raimsg_RaiMsg_ADD_ALL_ATTRS 1023L
/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raimsg_RaiMsg_Create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    ReUse
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_ReUse__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    ReUse
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_ReUse__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetProtocol
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsg_GetProtocol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetProtocolString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_GetProtocolString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    MsgTypeToString
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_MsgTypeToString
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    StringToMsgType
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_rai_raimsg_RaiMsg_StringToMsgType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetMsgTypeString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_GetMsgTypeString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    SetMsgTypeString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_SetMsgTypeString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    RecTypeToString
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_RecTypeToString
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    StringToRecType
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_rai_raimsg_RaiMsg_StringToRecType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetRecTypeString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_GetRecTypeString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    SetRecTypeString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_SetRecTypeString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    RecStatusToString
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_RecStatusToString
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    StringToRecStatus
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_rai_raimsg_RaiMsg_StringToRecStatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetRecStatusString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_GetRecStatusString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    SetRecStatusString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_SetRecStatusString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    ClearForm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_ClearForm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Get
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiMsg_Get
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetBoolean
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiMsg_GetBoolean
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetByte
 * Signature: (JLjava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_com_rai_raimsg_RaiMsg_GetByte
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetShort
 * Signature: (JLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_rai_raimsg_RaiMsg_GetShort
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetInt
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsg_GetInt
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetLong
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_rai_raimsg_RaiMsg_GetLong
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetFloat
 * Signature: (JLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_rai_raimsg_RaiMsg_GetFloat
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetDouble
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_rai_raimsg_RaiMsg_GetDouble
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_GetString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetOpaque
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rai_raimsg_RaiMsg_GetOpaque
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetPartial
 * Signature: (JLjava/lang/String;)Lcom/rai/raimsg/Partial;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiMsg_GetPartial
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetBooleanArray
 * Signature: (JLjava/lang/String;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_rai_raimsg_RaiMsg_GetBooleanArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetByteArray
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rai_raimsg_RaiMsg_GetByteArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetShortArray
 * Signature: (JLjava/lang/String;)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_rai_raimsg_RaiMsg_GetShortArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetIntArray
 * Signature: (JLjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rai_raimsg_RaiMsg_GetIntArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetLongArray
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_rai_raimsg_RaiMsg_GetLongArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetFloatArray
 * Signature: (JLjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_rai_raimsg_RaiMsg_GetFloatArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetDoubleArray
 * Signature: (JLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_rai_raimsg_RaiMsg_GetDoubleArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetStringArray
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rai_raimsg_RaiMsg_GetStringArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Append
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Append__JLjava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendWithHint
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendWithHint
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendOpaque
 * Signature: (JLjava/lang/String;[BII)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendOpaque
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jint, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendUnsigned
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendUnsigned
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Append
 * Signature: (JLcom/rai/raimsg/RaiField;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Append__JLcom_rai_raimsg_RaiField_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendBoolean
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendBoolean
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendByte
 * Signature: (JLjava/lang/String;BZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendByte
  (JNIEnv *, jclass, jlong, jstring, jbyte, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendShort
 * Signature: (JLjava/lang/String;SZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendShort
  (JNIEnv *, jclass, jlong, jstring, jshort, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendInt
 * Signature: (JLjava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendInt
  (JNIEnv *, jclass, jlong, jstring, jint, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendLong
 * Signature: (JLjava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendLong
  (JNIEnv *, jclass, jlong, jstring, jlong, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendFloat
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    AppendDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_AppendDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Update
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Update__JLjava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateWithHint
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateWithHint
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateOpaque
 * Signature: (JLjava/lang/String;[BII)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateOpaque
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jint, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateUnsigned
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateUnsigned
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Update
 * Signature: (JLcom/rai/raimsg/RaiField;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Update__JLcom_rai_raimsg_RaiField_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateBoolean
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateBoolean
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateByte
 * Signature: (JLjava/lang/String;BZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateByte
  (JNIEnv *, jclass, jlong, jstring, jbyte, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateShort
 * Signature: (JLjava/lang/String;SZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateShort
  (JNIEnv *, jclass, jlong, jstring, jshort, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateInt
 * Signature: (JLjava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateInt
  (JNIEnv *, jclass, jlong, jstring, jint, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateLong
 * Signature: (JLjava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateLong
  (JNIEnv *, jclass, jlong, jstring, jlong, jboolean);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateFloat
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UpdateDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UpdateDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    UnPack
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_UnPack
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Pack
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsg_Pack__J_3BII
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Pack
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rai_raimsg_RaiMsg_Pack__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    PackSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsg_PackSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Activate
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiMsg_Activate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Rename
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiMsg_Rename
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Remove
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rai_raimsg_RaiMsg_Remove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    Print
 * Signature: (JLjava/io/OutputStream;ZLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_Print
  (JNIEnv *, jclass, jlong, jobject, jboolean, jstring, jboolean, jstring, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    PrintHex
 * Signature: (JLjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_PrintHex__JLjava_io_OutputStream_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    PrintHex
 * Signature: (Ljava/io/OutputStream;[BII)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_PrintHex__Ljava_io_OutputStream_2_3BII
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    PrintXML
 * Signature: (JLjava/io/OutputStream;IZLjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_PrintXML
  (JNIEnv *, jclass, jlong, jobject, jint, jboolean, jstring, jobjectArray);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    StrType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rai_raimsg_RaiMsg_StrType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    TypeStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rai_raimsg_RaiMsg_TypeStr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    ReadDataDictionary
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_ReadDataDictionary
  (JNIEnv *, jclass, jstring, jstring, jstring, jchar);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    SetDataDictionary
 * Signature: (Lcom/rai/raimsg/RaiMsg;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_SetDataDictionary
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    GetDataDictionary
 * Signature: ()Lcom/rai/raimsg/RaiMsg;
 */
JNIEXPORT jobject JNICALL Java_com_rai_raimsg_RaiMsg_GetDataDictionary
  (JNIEnv *, jclass);

/*
 * Class:     com_rai_raimsg_RaiMsg
 * Method:    initClasses
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_rai_raimsg_RaiMsg_initClasses
  (JNIEnv *, jclass, jclass, jclass, jclass, jclass, jclass, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
